apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prguard-ingress
  namespace: prguard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: prguard.local
      http:
        paths:
          - path: /webhook
            pathType: Prefix
            backend:
              service:
                name: webhook-service
                port:
                  number: 8000
