import json
import logging
import os
import smtplib
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from confluent_kafka import Consumer
from dotenv import load_dotenv
from prometheus_client import Counter, Histogram, start_http_server
from opentelemetry import propagate, trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("notifier")

STAGE_DURATION = Histogram(
    "pr_stage_duration_seconds", "Duration of each pipeline stage",
    ["service", "stage"],
    buckets=(0.1, 0.25, 0.5, 1, 2, 3, 5, 7.5, 10, 15, 20, 30),
)
STAGE_TOTAL = Counter(
    "pr_stage_total", "Count of pipeline stage outcomes",
    ["service", "stage", "outcome"],
)

OTEL_ENDPOINT = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4318")
provider = TracerProvider(resource=Resource.create({"service.name": "notifier"}))
provider.add_span_processor(BatchSpanProcessor(OTLPSpanExporter(endpoint=f"{OTEL_ENDPOINT}/v1/traces")))
trace.set_tracer_provider(provider)
tracer = trace.get_tracer("notifier")


def log_event(stage: str, trace_id: str, **fields):
    logger.info(json.dumps({"service": "notifier", "trace_id": trace_id, "stage": stage, **fields}))


def record_stage(stage: str, duration_ms: float, outcome: str = "success"):
    STAGE_DURATION.labels(service="notifier", stage=stage).observe(duration_ms / 1000)
    STAGE_TOTAL.labels(service="notifier", stage=stage, outcome=outcome).inc()


def extract_trace_id(msg) -> str:
    for key, value in msg.headers() or []:
        if key == "trace_id":
            return value.decode()
    return "unknown"


def extract_otel_context(msg):
    carrier = {k: v.decode() for k, v in (msg.headers() or [])}
    return propagate.extract(carrier)

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
GMAIL_USER = os.getenv("GMAIL_USER", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")
NOTIFY_EMAIL = os.getenv("NOTIFY_EMAIL", "")

consumer = Consumer({
    "bootstrap.servers": KAFKA_BOOTSTRAP_SERVERS,
    "group.id": "notifier-group",
    "auto.offset.reset": "earliest",
})


def should_notify(review: dict) -> bool:
    """只在 score <= 6 或有 HIGH 问题时发通知"""
    if review.get("score", 10) <= 6:
        return True
    issues = review.get("issues", [])
    if any(issue.get("severity") == "high" for issue in issues):
        return True
    return False


def format_score_emoji(score: int) -> str:
    if score >= 8:
        return "🟢"
    elif score >= 6:
        return "🟡"
    else:
        return "🔴"


def build_email_body(pr_number: int, repo: str, html_url: str, review: dict) -> str:
    score = review.get("score", 0)
    summary = review.get("summary", "No summary available")
    issues = review.get("issues", [])
    suggestions = review.get("suggestions", [])
    approved = review.get("approved", False)

    score_emoji = format_score_emoji(score)
    status = "✅ Approved" if approved else "❌ Changes Requested"

    # 构建 issues 部分
    issues_text = ""
    if issues:
        for issue in issues:
            severity = issue.get("severity", "low").upper()
            line = issue.get("line", "general")
            comment = issue.get("comment", "")
            if severity == "HIGH":
                emoji = "🔴"
            elif severity == "MEDIUM":
                emoji = "🟡"
            else:
                emoji = "🔵"
            issues_text += f"{emoji} {severity}   {line}\n         {comment}\n\n"
    else:
        issues_text = "No issues found.\n"

    # 构建 suggestions 部分
    suggestions_text = ""
    if suggestions:
        for s in suggestions:
            suggestions_text += f"💡 {s}\n"
    else:
        suggestions_text = "No suggestions.\n"

    body = f"""
────────────────────────────────
🤖 PRGuard AI Code Review Report
────────────────────────────────

PR Title : PR #{pr_number}
Repo     : {repo}
Score    : {score_emoji} {score}/10
Status   : {status}

Summary:
{summary}

─── Issues Found ──────────────────
{issues_text}
─── Suggestions ───────────────────
{suggestions_text}
─── Action Required ───────────────
👉 View PR: {html_url}

────────────────────────────────
Generated by PRGuard
"""
    return body


def send_email(subject: str, body: str, max_retries: int = 3):
    """通过 Gmail SMTP 发送邮件，失败自动重试最多 3 次"""
    msg = MIMEMultipart()
    msg["From"] = GMAIL_USER
    msg["To"] = NOTIFY_EMAIL
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    for attempt in range(1, max_retries + 1):
        try:
            with smtplib.SMTP("smtp.gmail.com", 587) as server:
                server.starttls()
                server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
                server.sendmail(GMAIL_USER, NOTIFY_EMAIL, msg.as_string())
            print(f"[Notifier] Email sent to {NOTIFY_EMAIL}")
            return
        except smtplib.SMTPException as e:
            print(f"[Notifier] SMTP error (attempt {attempt}/{max_retries}): {e}")
            if attempt < max_retries:
                time.sleep(2 ** attempt)  # 指数退避: 2s, 4s
            else:
                print(f"[Notifier] Failed to send email after {max_retries} attempts")


def process_event(event: dict, trace_id: str = "unknown", otel_context=None):
    with tracer.start_as_current_span("notify", context=otel_context) as span:
        span.set_attribute("prguard.trace_id", trace_id)

        t0 = time.perf_counter()
        pr_number = event.get("pr_number")
        repo = event.get("repo_full_name", "")
        html_url = event.get("html_url", "")
        review = event.get("review", {})

        if not should_notify(review):
            print(f"[Notifier] PR #{pr_number} score {review.get('score')}/10 — no notification needed")
            duration_ms = (time.perf_counter() - t0) * 1000
            log_event("notify", trace_id, pr_number=pr_number, sent=False, duration_ms=round(duration_ms, 2))
            record_stage("notify", duration_ms)
            return

        score = review.get("score", 0)
        score_emoji = format_score_emoji(score)
        subject = f"[PRGuard] ⚠️ PR #{pr_number} needs attention — Score: {score_emoji} {score}/10"
        body = build_email_body(pr_number, repo, html_url, review)

        send_email(subject, body)
        print(f"[Notifier] PR #{pr_number} — notified {NOTIFY_EMAIL} (score: {score}/10)")
        duration_ms = (time.perf_counter() - t0) * 1000
        log_event("notify", trace_id, pr_number=pr_number, sent=True, duration_ms=round(duration_ms, 2))
        record_stage("notify", duration_ms)


def main():
    start_http_server(9100)
    consumer.subscribe(["ai-results"])
    print("[Notifier] Started, waiting for AI review results...")

    try:
        while True:
            msg = consumer.poll(timeout=1.0)
            if msg is None:
                continue
            if msg.error():
                print(f"[Notifier] Consumer error: {msg.error()}")
                continue

            event = json.loads(msg.value().decode("utf-8"))
            trace_id = extract_trace_id(msg)
            otel_context = extract_otel_context(msg)
            try:
                process_event(event, trace_id, otel_context)
            except Exception as e:
                print(f"[Notifier] Error processing PR #{event.get('pr_number')}: {e}")
                STAGE_TOTAL.labels(service="notifier", stage="notify", outcome="error").inc()
    finally:
        consumer.close()


if __name__ == "__main__":
    main()
