import json
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from confluent_kafka import Consumer
from dotenv import load_dotenv

load_dotenv()

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
GMAIL_USER = os.getenv("GMAIL_USER", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")
NOTIFY_EMAIL = os.getenv("NOTIFY_EMAIL", "")

consumer = Consumer({
    "bootstrap.servers": KAFKA_BOOTSTRAP_SERVERS,
    "group.id": "notifier-group",
    "auto.offset.reset": "earliest",
})


def should_notify(review: dict) -> bool:
    """只在 score <= 6 或有 HIGH 问题时发通知"""
    if review.get("score", 10) <= 6:
        return True
    issues = review.get("issues", [])
    if any(issue.get("severity") == "high" for issue in issues):
        return True
    return False


def format_score_emoji(score: int) -> str:
    if score >= 8:
        return "🟢"
    elif score >= 6:
        return "🟡"
    else:
        return "🔴"


def build_email_body(pr_number: int, repo: str, html_url: str, review: dict) -> str:
    score = review.get("score", 0)
    summary = review.get("summary", "No summary available")
    issues = review.get("issues", [])
    suggestions = review.get("suggestions", [])
    approved = review.get("approved", False)

    score_emoji = format_score_emoji(score)
    status = "✅ Approved" if approved else "❌ Changes Requested"

    # 构建 issues 部分
    issues_text = ""
    if issues:
        for issue in issues:
            severity = issue.get("severity", "low").upper()
            line = issue.get("line", "general")
            comment = issue.get("comment", "")
            if severity == "HIGH":
                emoji = "🔴"
            elif severity == "MEDIUM":
                emoji = "🟡"
            else:
                emoji = "🔵"
            issues_text += f"{emoji} {severity}   {line}\n         {comment}\n\n"
    else:
        issues_text = "No issues found.\n"

    # 构建 suggestions 部分
    suggestions_text = ""
    if suggestions:
        for s in suggestions:
            suggestions_text += f"💡 {s}\n"
    else:
        suggestions_text = "No suggestions.\n"

    body = f"""
────────────────────────────────
🤖 PRGuard AI Code Review Report
────────────────────────────────

PR Title : PR #{pr_number}
Repo     : {repo}
Score    : {score_emoji} {score}/10
Status   : {status}

Summary:
{summary}

─── Issues Found ──────────────────
{issues_text}
─── Suggestions ───────────────────
{suggestions_text}
─── Action Required ───────────────
👉 View PR: {html_url}

────────────────────────────────
Generated by PRGuard
"""
    return body


def send_email(subject: str, body: str):
    """通过 Gmail SMTP 发送邮件"""
    msg = MIMEMultipart()
    msg["From"] = GMAIL_USER
    msg["To"] = NOTIFY_EMAIL
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_USER, NOTIFY_EMAIL, msg.as_string())

    print(f"[Notifier] Email sent to {NOTIFY_EMAIL}")


def process_event(event: dict):
    pr_number = event.get("pr_number")
    repo = event.get("repo_full_name", "")
    html_url = event.get("html_url", "")
    review = event.get("review", {})

    if not should_notify(review):
        print(f"[Notifier] PR #{pr_number} score {review.get('score')}/10 — no notification needed")
        return

    score = review.get("score", 0)
    score_emoji = format_score_emoji(score)
    subject = f"[PRGuard] ⚠️ PR #{pr_number} needs attention — Score: {score_emoji} {score}/10"
    body = build_email_body(pr_number, repo, html_url, review)

    send_email(subject, body)
    print(f"[Notifier] PR #{pr_number} — notified {NOTIFY_EMAIL} (score: {score}/10)")


def main():
    consumer.subscribe(["ai-results"])
    print("[Notifier] Started, waiting for AI review results...")

    try:
        while True:
            msg = consumer.poll(timeout=1.0)
            if msg is None:
                continue
            if msg.error():
                print(f"[Notifier] Consumer error: {msg.error()}")
                continue

            event = json.loads(msg.value().decode("utf-8"))
            try:
                process_event(event)
            except Exception as e:
                print(f"[Notifier] Error processing PR #{event.get('pr_number')}: {e}")
    finally:
        consumer.close()


if __name__ == "__main__":
    main()
